### ISSUE TITLE
The real-world experiment cannot work

### ISSUE THREAD

**Issue by Hgit007** [hongzimao/pensieve#119]
Hi,

Could you please help me figure out the issue when running the real-world experiment? 

I run `python run_video.py`.  It throw out  errors. I don't know what is the input parameters. 
![image](https://user-images.githubusercontent.com/39703828/95424100-27652980-0910-11eb-8ea9-f23276439f96.png)

Thanks in advance.

Best,

**Comment by hongzimao** [comment]
Note that `sys.argv[1]` is taking the input you provide right after `python run_video.py`. It raised this error because no input was provided.

Check out the example input we used in https://github.com/hongzimao/pensieve/blob/master/run_exp/run_traces.py#L31-L33 (e.g., `abr_algo` would correspond to `argv[1]` in your error message). Feel free to print out the command and see what exactly the example inputs are. 

Hope these help!

**Comment by Hgit007** [comment]
Thanks for your help.

I provide the input parameters. It seem I still didn't get it. I am not sure if I set the right process_id. Could you please help me? 
![image](https://user-images.githubusercontent.com/39703828/96674096-fe905b80-1335-11eb-985b-31575abf739b.png)

Besides, I am not well follow Line 47-L50. Why copy over these files?
![image](https://user-images.githubusercontent.com/39703828/96674874-ad816700-1337-11eb-986c-b1bb823de169.png)

Thank you.

Best,

**Comment by hongzimao** [comment]
The error is saying `../cooked_traces` is missing. Do you provide the right path to the trace file? Can you just make sure `python run_traces.py` or `python run_all_traces.py` run without any error --- this just makes sure all the dependencies and trace files are downloaded.

The copy command, IIRC, is copying over the chrome driver and the fresh chrome user state so that the experiment starts from a blank state (i.e., no caching of the video content or anything) or fair comparison. Check what's in the `chrome_user_dir` for more details.

**Comment by Hgit007** [comment]
Thanks for your reply. 

I have figured it out for running `python run_video.py` with the inputs. Here are some new issues. I get stuck here for a couple of days. I don't know how to solve it.

1. **The Chrome browser cannot open automatically** for all three files, `python run_video.py`, `python run_traces.py`, `python run_all_traces.py`. I check the chromedriver and the chrome version. Besides, I change chrome version _86.0.4240.75_ to _75.0.3770.80_. I try fix it by kinds of method. But it cannot work.

2.  **No record in _log_ file  in the folder `/run_exp/results/log`**for running `python run_traces.py` and `python run_traces.py`,  I need to run `../rl_server/simple_server.py`. After that, I  open the Chrome and type in the `url`, then hit the play button. The video can play normally. But the log file in `/run_exp/results` is empty. I print the parameters `err` , `out` and subprocess command. There is no error information. I don't know how to get the log information. 
![image](https://user-images.githubusercontent.com/39703828/97065579-5ae4bc80-157c-11eb-9aa0-8a5919ac3016.png)

3. For the three types of server, the port are all 8333, is there any conflict when running them together? 

Many thanks for your help.

**Comment by Hgit007** [comment]
Hi Hongzhi,
I know what happened. Thanks.

**Comment by hongzimao** [comment]
@Hgit007 could you share with us how you solved the issue, so that more people in the future can learn from it? Thank you!

**Comment by hy213817** [comment]
Hi, I have an empty file on results/. How did you solve it, can you help me?@Hgit007
