### ISSUE TITLE
plot_results.py outputs nothing?

### ISSUE THREAD

**Issue by Apolotary** [hongzimao/pensieve#2]
Hi, 

I have a problem with creating charts. I followed your guide and generated test data in test/results via rl_no_training.py, but when I run plot_results.py, the charts turn out to be empty.

I tried inspecting the plot_results.py code, and I found that in the block starting on line 121, schemes_check is never true and thus reward_all never gets any data.

Is there any workaround to fixing that? 

Thanks!!

**Comment by hongzimao** [comment]
You found the right block that breaks that code :) The checks there make sure the trace to plot is experienced by all schemes, which is defined in https://github.com/hongzimao/pensieve/blob/master/test/plot_results.py#L19. I guess you only ran Pensieve without others (e.g., `SIM_DP` for dynamic programming offline optimal). You will need to modify `SCHEMES` definition to plot only the schemes you ran (and recorded in `results/` folders). It didn't plot anything because it couldn't find logs corresponding to other schemes and couldn't compare.

**Comment by Apolotary** [comment]
Ah I see! So if I ran only rl_no_training.py, do I need to just have only sim_rl in SCHEMES and remove sim_dp?

**Comment by Apolotary** [comment]
Oh hey, that actually fixed it! I left only sim_rl in the array and everything worked.

Thanks again!!
