### ISSUE TITLE
trace data

### ISSUE THREAD

**Issue by SunshineJunFu** [hongzimao/pensieve#25]
I find  I can't download the raw fcc dataset from http://data.fcc.gov/download/measuring-broadband-america/2016/data-raw-2016-jun.tar.gz. Could you provide  fcc dataset ?

**Comment by drshashwat** [comment]
I am also facing the same issue. Please help.
Thanks.

**Comment by hongzimao** [comment]
We provided a copy of (cooked) data. Please refer to sim/README.md.

**Comment by drshashwat** [comment]
Thanks for your Reply.
I have downloaded the Cooked Traces but I am looking for Raw Traces.
Thanks.

**Comment by r02b** [comment]
I did some digging around the FCC website, and I think (can't be sure since I don't have the original data) that it's available here:
http://data.fcc.gov/download/measuring-broadband-america/2017/data-raw-2016-jun.tar.gz

@hongzimao , could you possibly check with your original files and confirm they're the same? Thanks in advance!
