### ISSUE TITLE
Question about pensieve

### ISSUE THREAD

**Issue by chaos5958** [hongzimao/pensieve#34]
Dear Hongzi,

I have couples of questions about Pensieve.

[About reward]
- Pensieve tests on 3 types of QoE, but each has different parameters for weighting re-buffering penalty. Why did you set it different and how did you pick the actual values (4.3 - linear, 2.6 - log, 8 - hd)? 

- Pensieve uses bitrate to hd reward mapping to calculate QoE (hd) (ex. 0.3 to 1, 0.75 to 2, ...). How did you pick the actual values (e.g. parameters for each bitrate)? 

[Minor]
- In plot_results.py, the evaluation excludes the first chunk as follows, `reward_all[scheme].append(np.sum(raw_reward_all[scheme][l][1:VIDEO_LEN]))`.
I agree it is minor issue, I want to know any reasons about this. 

- The default bitrate is set to 1, not as the lowest quality 0. I think the latter is somewhat common, but why pensieve chooses 1 as initial quality? It causes fair amount of re-buffering in many traces you provided in the dropbox. 
 
[Typo]
- There is a mistake in calculating log scale reward. The previous one uses highest bitrate resulting in negative value. 
original: `# log_bit_rate = np.log(VIDEO_BIT_RATE[bit_rate] / float(VIDEO_BIT_RATE[**-1**]))`
modified: `# log_last_bit_rate = np.log(VIDEO_BIT_RATE[last_bit_rate] / float(VIDEO_BIT_RATE[**0**]))`

Thanks.
Hyunho

**Comment by hongzimao** [comment]
[About reward]
- We picked the parameter in the same manner as the MPC paper (section 7.1.1, video parameters), namely 1-sec rebuffer/start-up time receives the same penalty as reducing the highest bitrate of a chunk.
- Well, to get this one we surveyed the number among people in our lab --- we asked a subjective question --- how much more satisfying would you feel if you watch HD versus non-HD, and 4K versus HD. The main point is that the utility function turns out to be S shape. If you have a better way to get unbiased estimation among larger population, please keep us updated.

You are very observant and careful. We are not claiming these numbers should be the right ones for production deployment---I think the right parameters need be obtained from a large scale survey study over a big population, and may very well differ person by person. We don't have access to this scale of survey study so we could only follow the existing convention. Nonetheless, a nice property for MPC and Pensieve is that the schemes are not so much hand tuned just for one set of parameters. The user can choose any QoE and the algorithm can adapt for that.

[Minoir]
- As you pointed out, the first bitrate is not controlled by the ABR algorithm. So we ignored the first reward for every scheme.
- I think the default BB in dash.js was using initial quality 1. So we followed the existing implementation.

[Typo]
- Negative value in the reward is fine (only the relative matters). We need to capture the concave utility function for log metric. The modified should also work.

**Comment by chaos5958** [comment]
Thank you for detailed answers! 
I have two more questions to ask.

**I think the paper summarizes average QoE over each trace on each CDF, and compares average of average QoE value on each bar graph. Since all video lengths used in the experiments is fixed to 192 secods, it seems alright**
**(Decprecated - I will remove it)** 1. Average QoE values in the figure8 and figure9
Since my average values are much bigger than the ones shown in the figure8, figure9, how did you calculate it? I add QoE for each trace and average these for all traces. For example, assume there is only one trace and streams a video with 360p with no rebuffering. Then, summation of QoE (linear) is 1.2*48=57.6. (1.2 represents for 1200kbps) However, the average QoE in the figure 8.(a) ranges from -0.5-2.5 which is pretty smaller than above bad condition.
I know QoE might be different from trace to trace, but overall values seem too low. 

**I realize that pensieve shows average QoE as CDF and than only calculates % on normalized average QoE.**
**(Decprecated - I will remove it)** _2. Calculation of %(percentage) over a positive number to a negative number._ 

_From my experiments and the results shown in the paper (figure8, figure9), QoE includes both negative and positive values. Therefore, there is an issue how to calculate percentage (%) when value ranges from minus to plus. (ex. https://www.excelcampus.com/functions/percentage-change-formula-negative-numbers/) I found that some outlier values highly affects average percentage. I know this is not critical on messages that pensieve delivers to us, but I'm curious how did you handle this issue. Did you post-process your data like normalization or mapping?_

Again, thanks a lot for answering all the questions, it really helps me a lot.
I highly appreciate your work.  

Thanks you.
Hyunho

**Comment by hongzimao** [comment]
1. It looks the QoE is not normalized to per step QoE in your case. The way we visualize the QoE can be found in https://github.com/hongzimao/pensieve/blob/master/test/plot_results.py

2. I think when we computed those relative values, they were all positive (the overall performance).
