### ISSUE TITLE
Multi Video Training

### ISSUE THREAD

**Issue by shubhamagarwal003** [hongzimao/pensieve#38]
Hi,
I wanted to try Multi Video training for Pensieve. I do see you have code for [multi_video_sim ](https://github.com/hongzimao/pensieve/tree/master/multi_video_sim). But couldn't see any documentation. Could you guide me how I can proceed with multi video training. Also I wanted to know your opinion on advantages of training Pensieve on multiple videos. Given we sample videos of different duration (say small <5min, medium ~ 5min to 30 min, large > 30min) would the network be able to perform well on new videos or there should be other factors considered while sampling the videos?

**Comment by hongzimao** [comment]
Notice that this experiment is simulated (since we didn't find hundreds of real videos). Before training the agent, run `generate_video.py` and `generate_test_video.py` to generate synthetic videos (with different chunk size, different number of bitrates, different durations, etc.). Then you run `multi_agent.py` similar to the training procedure in `sim`.

I think the agent should learn a sensible policy as long as you provide it enough number of examples that covers different durations. Let us know how this goes and anything you discover. Thanks!
