### ISSUE TITLE
Errors in plot_results.py

### ISSUE THREAD

**Issue by dyang37** [hongzimao/pensieve#40]
I'm trying to plot the result of pensieve(rl) and buffer based (bb) algorithm, but encountered the following error:
`Traceback (most recent call last):
  File "plot_results.py", line 227, in <module>
    main()
  File "plot_results.py", line 57, in main
    bit_rate.append(VIDEO_BIT_RATE[int(parse[6])])
ValueError: invalid literal for int() with base 10: '-10.714325277567443'`

Also another error is encountered when I try to plot the result of rl and dp:
`Traceback (most recent call last):
  File "plot_results.py", line 227, in <module>
    main()
  File "plot_results.py", line 70, in main
    assert rebuff >= -1e-4
AssertionError`

Note that I did change SCHEMES at line 19 to match the corresponding experiments in both cases. Any idea what would cause the errors above?
Thanks a lot!

**Comment by dyang37** [comment]
Also a quick question about the testing traces: what's the difference between train, bus, car, metro, etc.? Are the throughput distributions different in different cases?

**Comment by hammadmazhar1** [comment]
Have you checked the output files and seen if the output is formatted correctly. It seems like there is a conversion issue with the data that is being read, as in the second error. The testing traces of car, train bus, metro etc simply refer to the vehicle the measuring device was in. There would be differences in throughput due to speed, locations and the amount of other users in the same location and other factors.

**Comment by hongzimao** [comment]
The norway trace is collected and explained in this paper (citation 37 in pensieve): https://dl.acm.org/citation.cfm?id=2483991
