### ISSUE TITLE
Question regarding bit rate selection

### ISSUE THREAD

**Issue by HamzaOulu** [hongzimao/pensieve#56]
Hello,
I was trying to understand your code. The bit rate selection in the training environment is defined as below,

# compute action probability vector
            action_prob = actor.predict(np.reshape(state, (1, S_INFO, S_LEN)))
            action_cumsum = np.cumsum(action_prob)
            bit_rate = (action_cumsum > np.random.randint(1, RAND_RANGE) / float(RAND_RANGE)).argmax()
            
and when I go in the testing file the same bit rate selection algorithm is used. I wanted to ask if I use a randomized bit rate selection approach in the training method and then use the above algorithm in the testing what difference will it make? Also what is the reason of using same algorithm of bit rate selection in training and testing?

Br,
Hamza

**Comment by hongzimao** [comment]
I don't quite get your question---for machine learning algorithms in general, we usually use the same approach for training and testing.

You might want to ask if we should take the action with max probability in testing, instead of doing a sampling like training. This is reasonable; you can try that. The reason we do the same here is we don't want to deviate in the state space when testing.

You also might want to ask what `np.random.randint(1, RAND_RANGE) / float(RAND_RANGE)).argmax()` is doing. This is quantizing the sampling method for numerical stability (this issue should be long gone for now; it's an issue with old versions of tensorflow).
